name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Get basic dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget git cmake tcsh
        sudo apt-get install -y build-essential
    - name: Create installation directory
      run: mkdir install
    - name: Set number of cores for compilation
      run: |
        echo "::set-env name=MAKEFLAGS::-j$(nproc)"
    - name: Get and compile dependencies
      run: tcsh ./dependencies.sh $HOME/install
    - name: Get GRASS GIS compile time dependencies
      run: |
        sudo apt-get install -y flex bison zlib1g-dev libpng-dev libgl1-mesa-dev libglu1-mesa-dev libfftw3-dev libcairo-dev python3-six
    - name: Get and compile GRASS GIS
      run: tcsh ./compile.sh $HOME/install
    - name: Add the bin directory to PATH
      run: |
        echo "::add-path::$HOME/install/bin"
    - name: Basic test of GRASS GIS
      run: tcsh ./test.sh
    - name: Thorough test of GRASS GIS
      run: tcsh ./test-thorough.sh
